"use client";
import Navigation from "@/components/navigation/navigation.jsx";
import "./globals.css";
import Providers from "@/providers";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="relative z-[9999] flex justify-center mx-auto max-w-[480px] h-screen overflow-auto bg-[#2b2a2a]">
            {children}
            <Navigation />
          </div>
        </Providers>
      </body>
    </html>
  );
}
