"use client";
import Providers from "../providers";
import Navigation from "../components/navigation/navigation";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENTID}>
          <Providers>
            <div className="relative z-[9999] flex justify-center mx-auto max-w-[480px] h-screen overflow-auto bg-[#2b2a2a]">
              {children}
              <Navigation />
            </div>
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
